apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
        - name: api
          image: llm-api-server:test
          ports:
            - containerPort: 8000
