FROM python:3.10-slim

WORKDIR /app

COPY inference/ inference/
COPY inference/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["uvicorn", "inference.server:app", "--host", "0.0.0.0", "--port", "8000"]

